Vagrant.configure("2") do |config|
  
    config.vm.define "client" do |client|
      client.vm.box = "generic/ubuntu2204"
      client.vm.hostname = "client"
      
      client.vm.provider "virtualbox" do |vb|
        vb.name = "client-vm"
        vb.memory = "1024"
        vb.cpus = 2
      end
  
      client.vm.network "private_network", ip: "192.168.56.113"
    end
  
    config.vm.define "backup" do |backup|
      backup.vm.box = "generic/ubuntu2204"
      backup.vm.hostname = "backup"
      
      backup.vm.provider "virtualbox" do |vb|
        vb.name = "backup-vm"
        vb.memory = "1024"
        vb.cpus = 2
      end

      backup.vm.network "private_network", ip: "192.168.56.114"
    end
  end
