Vagrant.configure("2") do |config|
  
    config.vm.define "lab4" do |lab4|
      lab4.vm.box = "generic/rocky9"
      lab4.vm.hostname = "lab4"
      
      lab4.vm.provider "virtualbox" do |vb|
        vb.name = "lab4-virtualbox"
        vb.memory = "3072"
        vb.cpus = 2
  
      lab4.vm.network "private_network", ip: "192.168.56.110"
    end
  end
end
