# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Specify the base box
    config.vm.box = "generic/ubuntu2204"
  
    # Configure a private network with a static IP
    config.vm.network "private_network", ip: "192.168.56.115"
  
    # VM configuration
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
  
      # Enable nested virtualization
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end
  end
