Vagrant.configure("2") do |config|
  
    config.vm.define "lab2" do |lab2|
      lab2.vm.box = "generic/rocky9"
      lab2.vm.hostname = "lab2"
      
      lab2.vm.provider "virtualbox" do |vb|
        vb.name = "lab2-vm"
        vb.memory = "512"
        vb.cpus = 2
      end
  
      lab2.vm.network "private_network", ip: "192.168.56.101"
  
      # Provisioning script to set up users and passwords
      lab2.vm.provision "shell", inline: <<-SHELL
        echo "RootPassword!" | sudo passwd root --stdin
        sudo useradd test
        echo "test:Password!" | sudo chpasswd
        sudo sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
        sudo sed -i 's/^PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo systemctl restart sshd
      SHELL
    end
  end
